# Generated by Django 5.2.3 on 2025-06-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
