# Generated by Django 4.2.7 on 2025-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="medicine",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("full", "Full"),
                    ("need", "Need Stock"),
                    ("out", "Out of Stock"),
                ],
                default="full",
                max_length=10,
            ),
        ),
    ]
