# Generated by Django 4.2.7 on 2025-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0005_medicine_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer",
        ),
    ]
