# Generated by Django 4.2.7 on 2025-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_remove_medicine_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
