# Generated by Django 4.2.7 on 2025-06-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        ("beds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_notes", models.TextField()),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                ("is_discharged", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("normal", "Normal"),
                            ("discharged", "Discharged"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="beds.bed"
                    ),
                ),
                ("doctors", models.ManyToManyField(to="doctors.doctor")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
