# Generated by Django 4.2.7 on 2025-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_number", models.CharField(max_length=10, unique=True)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[("Normal", "Normal Bed"), ("ICU", "ICU Bed")],
                        max_length=10,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "assigned_patient",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BedWaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[("Normal", "Normal Bed"), ("ICU", "ICU Bed")],
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
