# Generated by Django 4.2.7 on 2025-06-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("beds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bedwaitinglist",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="bedwaitinglist",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
    ]
