# Generated by Django 4.2.7 on 2025-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("guardian_name", models.CharField(max_length=100)),
                ("guardian_phone", models.CharField(max_length=20)),
                ("medical_history", models.TextField(blank=True)),
                (
                    "diagnosis_report",
                    models.TextField(
                        blank=True, help_text="Diagnosis report or file path"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
