# Generated by Django 4.2.7 on 2025-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                (
                    "availability",
                    models.CharField(help_text="e.g. Mon-Fri 9am-5pm", max_length=100),
                ),
                (
                    "assigned_patients",
                    models.TextField(
                        blank=True, help_text="Comma-separated patient IDs or names"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
